### ISSUE TITLE
Get customers with a specific address

### ISSUE THREAD

**Issue by Kathryn-z** [CSCI-GA-2820-FA23-001/customers#5]
**As a** customer service manager
**I need** to get customers with a specific address
**So that** I can analyze the information about our customer base, and see if certain areas have large numbers of customers.
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given there are several customers in the database
 When I call the get customers with a specific address API
 Then a list of customers with that address is displayed
```

**Comment by yuchenzhao726** [comment]
I think this issue can be solved by this one: [Read a Customer]
