### ISSUE TITLE
Green test stuck while service is running

### ISSUE THREAD

**Issue by yuchenzhao726** [CSCI-GA-2820-FA23-001/customers#67]
**Describe the bug**
Green test get stuck at first step while the service is running

**To Reproduce**
1. make run in the terminal
2. go to the browser and create a customer
3. back to vscode and open another terminal
4. make test

**Expected behavior**
It should not stuck

**Observed behavior**
It is stuck

**Additional context**
Try to set up a test database for tests

**Comment by naomiyjchen** [comment]
It also stucked on openshift as well. Green test won't continue after the below message:

```
***** Running Tests *****
[1mGreen 3.4.3, Coverage 7.1.0, Python 3.11.6
[0m
[1mtests.test_cli_commands[0m
  TestFlaskCLI
[32m.   It should call the db-create command[0m
```

**Comment by naomiyjchen** [comment]
Not sure how to solve this problem locally but it works well on openshift now!
