### ISSUE TITLE
List Customers

### ISSUE THREAD

**Issue by Lichengxi0507** [CSCI-GA-2820-FA23-001/customers#8]
**As an** account manager
**I need** a way to get all the customers information in the database
**So that** I can browse all the customers information faster and easier
   
 ### Details and Assumptions
 * show all columns of information
 * each customer per line
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a customer database
 When I call the List API
 Then that returns all the customers information in the database
```

**Comment by naomiyjchen** [comment]
It seems like line 52 -66 in of the`list_customers()` are not tested. I think this is because you called the `self._create_customers()` which is not defined.

**Comment by Lichengxi0507** [comment]
yes, but I don't know how to def it
